{
  pkgs,
  ...
}:
{
  imports = [
    ./waybar.nix
  ];

  xdg.configFile."niri/config.kdl".source = ./config.kdl;

  # Walker launcher with cyberpunk theme.
  # Replaces rofi — Walker is a GTK4 Wayland launcher that supports
  # click-outside-to-close (unlike rofi on Wayland).
  programs.walker = {
    enable = true;
    runAsService = true;
    config = {
      theme = "cyberpunk";
      click_to_close = true;
      close_when_open = true;
      single_click_activation = true;
    };
    themes = {
      cyberpunk = {
        style = builtins.readFile ./themes/walker-cyberpunk.css;
      };
    };
  };

  # Taskwarrior configuration.
  xdg.configFile."task/taskrc".text = ''
    # Taskwarrior configuration — generated by NixOS.
    data.location=~/.local/share/task

    # Default task attributes.
    default.project=
    default.priority=

    # Sort pending tasks by urgency (highest first).
    report.next.sort=urgency-
    report.next.filter=status:pending limit:10

    # Waybar report used by the custom/todo module.
    report.waybar.description=Waybar
    report.waybar.columns=due.relative,description.count
    report.waybar.labels=Due,Task
    report.waybar.sort=urgency-

    # Keep history compact.
    purge.on-sync=yes
  '';

  # Tools invoked by niri binds in config.kdl.
  home.packages = with pkgs; [
    brightnessctl  # F5/F6 brightness keys
  ];

  programs'.waybar = {
    enable = true;
    enableNiriIntegration = true;
  };

  # Configure fcitx5 input methods: English (keyboard-gb) + Chinese (pinyin).
  xdg.configFile."fcitx5/profile".text = ''
    [Groups/0]
    Name="Default"
    Default Layout=gb
    DefaultIM=keyboard-gb

    [Groups/0/Items/0]
    Name=keyboard-gb
    Layout=

    [Groups/0/Items/1]
    Name=pinyin
    Layout=

    [GroupOrder]
    0="Default"
  '';

  # Cyberpunk fcitx5 theme (matches waybar/walker palette).
  xdg.dataFile."fcitx5/themes/cyberpunk/theme.conf".source = ./themes/fcitx5-cyberpunk.conf;

  # Use the cyberpunk theme for the classic UI.
  xdg.configFile."fcitx5/conf/classicui.conf".text = ''
    Vertical Center=False
    PerScreenDPI=True
    UseDarkTheme=False
    Theme=cyberpunk
  '';

  home.pointerCursor = {
    enable = true;
    package = pkgs.bibata-cursors;
    name = "Bibata-Modern-Classic";
    size = 24;
    gtk.enable = true;
    x11.enable = true;
  };
}
