[workspace]
members = [
  "media-control",
  "ocr-screenshot",
  "preview-panel",
  "rofi-audio",
  "rofi-clipboard",
  "rofi-network-manager",
  "waybar-timer",
  "webcam-crop",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
strip = true
